--CREATE TABLE pessoa (
--    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
--    nome VARCHAR(50) NOT NULL,
--    logradouro VARCHAR(50),
--    numero VARCHAR(50),
--    complemento VARCHAR(50),
--    bairro VARCHAR(50),
--    cep VARCHAR(50),
--    cidade VARCHAR(50),
--    estado VARCHAR(50),
--    ativo BOOLEAN
--) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
--INSERT INTO pessoa (nome, logradouro, numero, complemento, bairro, cep, cidade, estado, ativo) VALUES
--('Adalberto','Rua B','400','Ao lado da biqueira','Caxambu','23012-211','Rio de Janeiro','Rio de Janeiro',true);
----
----INSERT INTO pessoa (nome, logradouro, numero, estado, ativo) values
----('Rafael'),
----('Estrada da Morte'),
----('16'),
----('Distrito Federal'),
----(true);
----
----
----INSERT INTO pessoa (nome, cep, numero, estado, ativo) values
----('João Roberto'),
----('15524-111'),
----('1442'),
----('Amazonas'),
----(false);
----
--
